name: iot-thingy52
version: "1.0.0"
summary: thingy52 Application Snap
description: A SNAP that simply reads thingy52 sensors and sends vi MQTT.
architectures: [armhf]
confinement: strict
grade: stable

parts:
  iot-thingy52:
    plugin: cmake
    source: src
    stage-packages:
        - libjansson-dev
apps:
  iot-thingy52:
    command: bin/thingy
    plugs: &plugs [network, network-control, bluetooth-control]
